# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/example

baseURL: https://example.com/
title: Hugo Book
theme: hugo-book
disableKinds: ['taxonomy', 'taxonomyTerm']
# themesDir: ../..

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Code highlight
# pygmentsStyle: monokailight
pygmentsCodeFences: true

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false/off to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC: 3

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection: docs

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/alex-shpak/hugo-book

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master/exampleSite/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: 'Jan 2, 2006'
